### PR TITLE
added gray matter loader to related project

### PR DESCRIPTION
**Pull request by ajaymathur**
This is related to https://github.com/jonschlinkert/gray-matter/issues/81

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> Especially since this package was written by Atlassian to support

I'm totally fine with it, feel free to merge it in once you are happy with it. thanks for asking!

**Comment by ajaymathur** [comment]
I am working on docs of the package. I will update once it is ready. 🙂

**Comment by robertmassaioli** [comment]
> I am working on docs of the package. I will update once it is ready. 🙂

I'll sync on this next week.

**Comment by ajaymathur** [comment]
Hey @robertmassaioli , I have updated the readme of [gray-matter-loader](https://www.npmjs.com/package/gray-matter-loader)

**Comment by robertmassaioli** [comment]
Much better readme. I can see the value clearly now. Merging this in!

**Pull request merged**
