### PR TITLE
Lock down coffee-script to remove error being thrown in 1.12.8

### PR DESCRIPTION
**Pull request by aljopro**
coffee-script 1.12.8 is causing an error. To suppress the error we should lock down coffee-script to 1.12.7 until the error is resolved.

### CODE REVIEW

**Comment by aljopro** [comment]
@jonschlinkert An update to coffeescript is causing clean dev installs to fail. It's ultimately an issue on the coffeescript repo side but to get things working I've locked down the version of coffeescript in this PR.

**Comment by julmot** [comment]
Should work now @aljopro, due to this fix: https://github.com/jashkenas/coffeescript/issues/4805#issuecomment-348237307

**Comment by jonschlinkert** [comment]
since this was fixed, is there still a reason to merge this?  thanks for the pr

**Comment by aljopro** [comment]
@jonshlinkert only if you want to move to the preferred coffee script repo. Or you can wait to do this when you have a more substantial update. Your choice.

**Pull request merged**
