### PR TITLE
explain how to enable toml and cson (#25)

### PR DESCRIPTION
**Pull request by marcoms**

### CODE REVIEW

**Comment by jonschlinkert** [comment]
closing since the documentation has changed and this project has always used a template to generate the readme

**Comment by marcoms** [comment]
@jonschlinkert What are the next steps in this case? Would you like me to change `.verb.md` instead?

**Comment by jonschlinkert** [comment]
Sorry, I would have asked you to update .verb.md but I made a bunch of changes locally that I'm going to push up as soon as I have a chance, and I didn't want to impose. But if you'd like to do that, I would still gladly accept a pr.

**Comment by marcoms** [comment]
No problem, thanks for the context. I'll defer the PR until your changes land 👍

**Pull request closed without merging**
